DOMAIN = "tv_auto_scheduler"

DEFAULT_RULES_FILE = "/config/tv_auto_scheduler/rules.csv"
DEFAULT_NAMED_TIME_RANGES_FILE = "/config/tv_auto_scheduler/named_time_ranges.csv"
DEFAULT_CHANNELS_FILE = "/config/tv/channels.yaml"
DEFAULT_OPEN_EPG_EXPORT_FILE = "/config/tv_auto_scheduler/open_epg_snapshot.json"
CHANNEL_DATABASE_ENTITY = "sensor.tv_channel_database"

DEFAULT_PRE_CALENDAR = "calendar.pre_tv"
DEFAULT_TV_CALENDAR = "calendar.televisie"

CONF_RULES_FILE = "rules_file"
CONF_DRY_RUN = "dry_run"
CONF_DRY_RUN_LOG = "dry_run_log"
CONF_DRY_RUN_LOG_FILE = "dry_run_log_file"
CONF_PRE_CALENDAR = "pre_calendar"
CONF_TV_CALENDAR = "tv_calendar"
CONF_SHOW_MISSING_EPG = "show_missing_epg"
CONF_CHANGE_LOG = "change_log"
CONF_CHANGE_LOG_FILE = "change_log_file"
CONF_CANALPLUS_AUTHORIZATION = "canalplus_authorization"
CONF_CANALPLUS_CHANNELS = "canalplus_channels"
CONF_CHANNELS_FILE = "channels_file"
CONF_COMPARISON_REPORT_FILE = "comparison_report_file"
CONF_OPEN_EPG_EXPORT_FILE = "open_epg_export_file"
CONF_ONLY_SCHEDULED_PROGRAMMES = "only_scheduled_programmes"
CONF_SHOW_MATCHING_PROGRAMMES = "show_matching_programmes"

SERVICE_SCAN = "scan"
SERVICE_COMPARE_CANALPLUS = "compare_canalplus"
SERVICE_EXPORT_OPEN_EPG = "export_open_epg"

CSV_RULE_ID = "rule-id"
CSV_ENABLED = "enabled"
CSV_CHANNEL = "channel"
CSV_PROGRAMME = "programme"
CSV_PRE = "pre"
CSV_TV = "tv"
CSV_DELETE_AFTER_USE = "flag-delete-after-use"
CSV_NAMED_TIME_RANGE = "named-time-range"
CSV_FILTER_START_DAY = "filter-start-day"
CSV_FILTER_START_TIME = "filter-start-time"
CSV_FILTER_END_TIME = "filter-end-time"
